# Site settings
title: Phani Atmakur
general_email: phani@kernalinc.com

description: > # this means to ignore newlines until "baseurl:"
  I have a strong passion for technology. I write mostly about Python, Django, Pandas, Data Science, Machine Learning, Big Data and lot more.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://py404.github.io" # the base hostname & protocol for your site

github_username: py404
linkedin_username: phaniatmakur
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title