# Site settings
title: Phani Atmakur
general_email: phani@kernalinc.com

description: > # this means to ignore newlines until "baseurl:"
  I am a Python Developer and a Data Scientist living in New Zealand. I currently work at Institute of Environmental Science & Research (ESR) in Christchurch.

baseurl: ""
repository: py404/py404.github.io

url: "https://py404.github.io" # the base hostname & protocol for your site


### Plugins ###
plugins:
  - jemoji

### Pagination

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/** # For Documentation Only

### Author Info ###
author:
  name: Phani Atmakur
  image: avatar/phani_avatar.jpg
  email: phani@kernalinc.com
  github: py404
  linkedin: phaniatmakur
  instagram: phani_reddy21

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: UA-43896612-1

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope: # For Documentation Only
      path: "" # For Documentation Only
      type: "elements" # For Documentation Only
    values: # For Documentation Only
      layout: "element" # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
